packages:
  - 'apps/*'
  - 'packages/*'

# https://pnpm.io/settings
shamefullyHoist: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  argon2: true
  esbuild: true
  prisma: true
  unrs-resolver: true
